core/admin/mailu/sso/forms.py
from wtforms import validators, fields
from flask_babel import lazy_gettext as _
import flask_wtf

class LoginForm(flask_wtf.FlaskForm):
    class Meta:
        csrf = False
    email = fields.StringField(_('E-mail'), [validators.Email(), validators.DataRequired()], render_kw={'autofocus': True})
    pw = fields.PasswordField(_('Password'), [validators.DataRequired()])
    pwned = fields.HiddenField(label='', default=-1)
    submitWebmail = fields.SubmitField(_('Sign in'))
    submitAdmin = fields.SubmitField(_('Sign in'))

class PWChangeForm(flask_wtf.FlaskForm):
    oldpw = fields.PasswordField(_('Current password'), [validators.DataRequired()])
    pw = fields.PasswordField(_('New password'), [validators.DataRequired()])
    pw2 = fields.PasswordField(_('New password (again)'), [validators.DataRequired()])
    pwned = fields.HiddenField(label='', default=-1)
    submit = fields.SubmitField(_('Change password'))

core/admin/mailu/sso/__init__.py
from flask import Blueprint

sso = Blueprint('sso', __name__, static_folder=None, template_folder='templates')

from mailu.sso.views import *

core/admin/mailu/sso/views/__init__.py
__all__ = [
    'base', 'languages'
]

core/admin/mailu/sso/views/base.py
from werkzeug.utils import redirect
from mailu import models, utils
from mailu.sso import sso, forms
from mailu.ui import access

from flask import current_app as app
from flask_babel import lazy_gettext as _
import flask
import flask_login
import secrets
import ipaddress
from urllib.parse import urlparse, urljoin, unquote

@sso.route('/login', methods=['GET', 'POST'])
def login():
    if flask.request.headers.get(app.config['PROXY_AUTH_HEADER']) and not 'noproxyauth' in flask.request.url:
        return _proxy()

    client_ip = flask.request.headers.get('X-Real-IP', flask.request.remote_addr)
    client_port = flask.request.headers.get('X-Real-Port', None)
    form = forms.LoginForm()

    fields = []

    if 'url' in flask.request.args and not 'homepage' in flask.request.url:
        fields.append(form.submitAdmin)
    else:
        form.submitAdmin.label.text = form.submitAdmin.label.text + ' Admin'
        form.submitWebmail.label.text = form.submitWebmail.label.text + ' Webmail'
        if str(app.config["WEBMAIL"]).upper() != "NONE":
            fields.append(form.submitWebmail)
        if str(app.config["ADMIN"]).upper() != "FALSE":
            fields.append(form.submitAdmin)
    fields = [fields]

    if form.validate_on_submit():
        if destination := _has_usable_redirect():
            pass
        else:
            if form.submitAdmin.data:
                destination = app.config['WEB_ADMIN']
            elif form.submitWebmail.data:
                destination = app.config['WEB_WEBMAIL']
        device_cookie, device_cookie_username = utils.limiter.parse_device_cookie(flask.request.cookies.get('rate_limit'))
        username = form.email.data
        if not utils.is_app_token(form.pw.data):
            if username != device_cookie_username and utils.limiter.should_rate_limit_ip(client_ip):
                flask.flash(_('Too many attempts from your IP (rate-limit)'), 'error')
                return flask.render_template('login.html', form=form, fields=fields)
            if utils.limiter.should_rate_limit_user(username, client_ip, device_cookie, device_cookie_username):
                flask.flash(_('Too many attempts for this user (rate-limit)'), 'error')
                return flask.render_template('login.html', form=form, fields=fields)
        user = models.User.login(username, form.pw.data)
        if user:
            flask.session.regenerate()
            flask_login.login_user(user)
            if user.change_pw_next_login:
                flask.session['redirect_to'] = destination
                destination = flask.url_for('sso.pw_change')
            response = flask.redirect(destination)
            response.set_cookie('rate_limit', utils.limiter.device_cookie(username), max_age=31536000, path=flask.url_for('sso.login'), secure=app.config['SESSION_COOKIE_SECURE'], httponly=True)
            flask.current_app.logger.info(f'Login attempt for: {username}/sso/{flask.request.headers.get("X-Forwarded-Proto")} from: {client_ip}/{client_port}: success: password: {form.pwned.data}')
            if msg := utils.isBadOrPwned(form):
                flask.flash(msg, "error")
            return response
        else:
            utils.limiter.rate_limit_user(username, client_ip, device_cookie, device_cookie_username, form.pw.data) if models.User.get(username) else utils.limiter.rate_limit_ip(client_ip, username)
            flask.current_app.logger.info(f'Login attempt for: {username}/sso/{flask.request.headers.get("X-Forwarded-Proto")} from: {client_ip}/{client_port}: failed: badauth: {utils.truncated_pw_hash(form.pw.data)}')
            flask.flash(_('Wrong e-mail or password'), 'error')
    return flask.render_template('login.html', form=form, fields=fields)

@sso.route('/pw_change', methods=['GET', 'POST'])
@access.authenticated
def pw_change():
    client_ip = flask.request.headers.get('X-Real-IP', flask.request.remote_addr)
    client_port = flask.request.headers.get('X-Real-Port', None)
    form = forms.PWChangeForm()

    if form.validate_on_submit():
        if msg := utils.isBadOrPwned(form):
            flask.flash(msg, "error")
            return flask.redirect(flask.url_for('sso.pw_change'))
        if form.oldpw.data == form.pw2.data:
            # TODO: fuzzy match?
            flask.flash(_("The new password can't be the same as the old password"), "error")
            return flask.redirect(flask.url_for('sso.pw_change'))
        if form.pw.data != form.pw2.data:
            flask.flash(_("The new passwords don't match"), "error")
            return flask.redirect(flask.url_for('sso.pw_change'))
        user = models.User.login(flask_login.current_user.email, form.oldpw.data)
        if user:
            flask.session.regenerate()
            flask_login.login_user(user)
            user.set_password(form.pw.data, keep_sessions=set(flask.session))
            user.change_pw_next_login = False
            models.db.session.commit()
            flask.current_app.logger.info(f'Forced password change by {user} from: {client_ip}/{client_port}: success: password: {form.pwned.data}')
            destination = flask.session.pop('redir_to', None) or app.config['WEB_ADMIN']
            return flask.redirect(destination)
        flask.flash(_("The current password is incorrect!"), "error")

    return flask.render_template('pw_change.html', form=form)

@sso.route('/logout', methods=['GET'])
@access.authenticated
def logout():
    flask_login.logout_user()
    flask.session.destroy()
    response = flask.redirect(app.config['PROXY_AUTH_LOGOUT_URL'] or flask.url_for('.login'))
    for cookie in ['roundcube_sessauth', 'roundcube_sessid', 'smsession']:
        response.set_cookie(cookie, 'empty', expires=0)
    return response

"""
Redirect to the url passed in parameter if any; Ensure that this is not an open-redirect too...
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
"""
def _has_usable_redirect(is_proxied=False):
    if 'homepage' in flask.request.url and not is_proxied:
        return None
    if url := flask.request.args.get('url'):
        target = urlparse(urljoin(flask.request.url, unquote(url)))
        if target.netloc == urlparse(flask.request.url).netloc:
            return target.geturl()
    return None

"""
https://mailu.io/master/configuration.html#header-authentication-using-an-external-proxy
"""
def _proxy():
    proxy_ip = flask.request.headers.get('X-Forwarded-By', flask.request.remote_addr)
    ip = ipaddress.ip_address(proxy_ip)
    client_ip = flask.request.headers.get('X-Real-IP', flask.request.remote_addr)
    if not any(ip in cidr for cidr in app.config['PROXY_AUTH_WHITELIST']):
        flask.current_app.logger.error(f'Login failed by proxy - not on whitelist: from {client_ip} through {flask.request.remote_addr}.')
        return flask.abort(500, '%s is not on PROXY_AUTH_WHITELIST' % proxy_ip)

    email = flask.request.headers.get(app.config['PROXY_AUTH_HEADER'])
    if not email:
        flask.current_app.logger.error(f'Login failed by proxy - no header: from {client_ip} through {flask.request.remote_addr}.')
        return flask.abort(500, 'No %s header' % app.config['PROXY_AUTH_HEADER'])

    url = _has_usable_redirect(True) or app.config['WEB_ADMIN']

    user = models.User.get(email)
    if user:
        flask.session.regenerate()
        flask_login.login_user(user)
        flask.current_app.logger.info(f'Login succeeded by proxy created user: {user} from {client_ip} through {flask.request.remote_addr}.')
        return flask.redirect(url)

    if not app.config['PROXY_AUTH_CREATE']:
        flask.current_app.logger.warning(f'Login failed by proxy - does not exist: {user} from {client_ip} through {flask.request.remote_addr}.')
        return flask.abort(500, 'You don\'t exist. Go away! (%s)' % email)

    client_ip = flask.request.headers.get('X-Real-IP', flask.request.remote_addr)
    try:
        localpart, desireddomain = email.rsplit('@')
    except Exception as e:
        flask.current_app.logger.error('Error creating a new user via proxy for %s from %s: %s' % (email, client_ip, str(e)), e)
        return flask.abort(500, 'You don\'t exist. Go away! (%s)' % email)
    domain = models.Domain.query.get(desireddomain) or flask.abort(500, 'You don\'t exist. Go away! (domain=%s)' % desireddomain)
    if not domain.max_users == -1 and len(domain.users) >= domain.max_users:
        flask.current_app.logger.warning('Too many users for domain %s' % domain)
        return flask.abort(500, 'Too many users in (domain=%s)' % domain)
    user = models.User(localpart=localpart, domain=domain)
    user.set_password(secrets.token_urlsafe(), keep_sessions=set(flask.session))
    models.db.session.add(user)
    models.db.session.commit()
    flask.session.regenerate()
    flask_login.login_user(user)
    user.send_welcome()
    flask.current_app.logger.info(f'Login succeeded by proxy created user: {user} from {client_ip} through {flask.request.remote_addr}.')
    return flask.redirect(url)

core/admin/mailu/sso/views/languages.py
from mailu.sso import sso
import flask

@sso.route('/language/<language>', methods=['GET','POST'])
def set_language(language=None):
    if language:
        flask.session['language'] = language
    return flask.Response(status=200)

core/admin/mailu/sso/templates/base_sso.html
{%- import "macros.html" as macros %}
{%- import "bootstrap/utils.html" as utils %}
<!doctype html>
<html lang="{{ get_locale() }}" data-static="/static/">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% trans %}Admin page for{% endtrans %} {{ config["SITENAME"] }}">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Mailu-Admin | {{ config["SITENAME"] }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}">
  </head>
  <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars" title="{% trans %}toggle sidebar{% endtrans %}" aria-expanded="false"></i><span class="sr-only">{% trans %}toggle sidebar{% endtrans %}</span></a>
          </li>
          <li class="nav-item">
          {%- for page, url in path %}
            {%- if loop.index > 1 %}
            <i class="fas fa-greater-than text-xs text-gray" aria-hidden="true"></i>
            {%- endif %}
            {%- if url %}
            <a class="nav-link d-inline-block" href="{{ url }}" role="button">{{ page }}</a>
            {%- else %}
            <span class="nav-link d-inline-block">{{ page }}</span>
            {%- endif %}
          {%- endfor %}
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
              <i class="fas fa-language text-xl" aria-hidden="true" title="{% trans %}change language{% endtrans %}"></i><span class="sr-only">{% trans %}change language{% endtrans %}</span>
              <span class="badge badge-primary navbar-badge">{{ get_locale() }}</span></a>
            <div class="dropdown-menu dropdown-menu-right p-0" id="mailu-languages">
            {%- for locale in config.translations.values() %}
              <a class="dropdown-item{% if locale|string() == session['language'] %} active{% endif %}" href="{{ url_for('sso.set_language', language=locale) }}">{{ locale.get_language_name().title() }}</a>
            {%- endfor %}
            </div>
          </li>
        </ul>
      </nav>
      <aside class="main-sidebar sidebar-dark-primary nav-compact elevation-4">
        <a class="brand-link bg-mailu-logo"{% if config["LOGO_BACKGROUND"] %} style="background-color:{{ config["LOGO_BACKGROUND"] }}!important;"{% endif %}>
          <img src="{{ config["LOGO_URL"] if config["LOGO_URL"] else '/static/mailu.png' }}" width="33" height="33" alt="Mailu" class="brand-image mailu-logo img-circle elevation-3">
          <span class="brand-text font-weight-light">{{ config["SITENAME"] }}</span>
        </a>
        {%- include "sidebar_sso.html" %}
      </aside>
      <div class="content-wrapper text-sm">
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0">{%- block title %}{%- endblock %}</h1>
                <small>{% block subtitle %}{% endblock %}</small>
              </div>
              <div class="col-sm-6">
                {%- block main_action %}{%- endblock %}
              </div>
            </div>
          </div>
        </section>
        <div class="content">
          {{ utils.flashed_messages(container=False, default_category='success') }}
          {%- block content %}{%- endblock %}
        </div>
      </div>
      <footer class="main-footer">
        Built with <i class="fa fa-heart text-danger" aria-hidden="true"></i><span class="sr-only">love</span>
        using <a href="https://flask.palletsprojects.com/">Flask</a>
        and <a href="https://adminlte.io/themes/v3/index3.html">AdminLTE</a>.
        <span class="fa-pull-right">
          <i class="fa fa-code-branch" aria-hidden="true"></i><span class="sr-only">fork</span>
          on <a href="https://github.com/Mailu/Mailu">Github</a>
        </span>
      </footer>
    </div>
    <script src="{{ url_for('static', filename='vendor.js') }}"></script>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
  </body>
</html>

core/admin/mailu/sso/templates/form_sso.html
{%- extends "base_sso.html" %}

{%- block content %}
{%- call macros.card() %}
<form class="form" method="post" role="form">
  {{ form.hidden_tag() }}
  {{ macros.form_field(form.email) }}
  {{ macros.form_field(form.pw) }}
  {{ macros.form_fields(fields, label=False, class="btn btn-default") }}
</form>
{%- endcall %}
{%- endblock %}

core/admin/mailu/sso/templates/login.html
{%- extends "form_sso.html" %}

{%- block title %}
{% trans %}Sign in{% endtrans %}
{%- endblock %}

core/admin/mailu/sso/templates/pw_change.html
{%- extends "base_sso.html" %}

{%- block content %}
{%- call macros.card() %}
<form class="form" method="post" role="form">
  {{ form.hidden_tag() }}
  {{ macros.form_field(form.oldpw) }}
  {{ macros.form_field(form.pw) }}
  {{ macros.form_field(form.pw2) }}
  {{ macros.form_field(form.submit) }}
</form>
{%- endcall %}
{%- endblock %}

core/admin/mailu/sso/templates/sidebar_sso.html
<div class="sidebar text-sm">
  <nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" role="menu">
    <li class="nav-header text-uppercase text-primary" role="none">{% trans %}Go to{% endtrans %}</li>
    {%- if config['ADMIN'] %}
      <li class="nav-item">
        <a href="{{ url_for('ui.client') }}" class="nav-link">
          <i class="nav-icon fa fa-laptop"></i>
          <p class="text">{% trans %}Client setup{% endtrans %}</p>
        </a>
      </li>
    {%- endif %}
      <li class="nav-item" role="none">
        <a href="{{ config["WEBSITE"] }}" target="_blank" class="nav-link" role="menuitem" rel="noreferrer">
          <i class="nav-icon fa fa-globe"></i>
          <p>{% trans %}Website{% endtrans %} <i class="fas fa-external-link-alt text-xs"></i></p>
        </a>
      </li>
      <li class="nav-item" role="none">
        <a href="https://mailu.io" target="_blank" class="nav-link" role="menuitem">
          <i class="nav-icon fa fa-life-ring"></i>
          <p class="text">{% trans %}Help{% endtrans %} <i class="fas fa-external-link-alt text-xs"></i></p>
        </a>
      </li>
    {#-
      Domain self-registration is only available when
       - Admin is available
       - Domain Self-registration is enabled
       - The current user is not logged on
    #}
    {%- if config['DOMAIN_REGISTRATION'] and not current_user.is_authenticated and config['ADMIN'] %}
      <li class="nav-item" role="none">
        <a href="{{ url_for('ui.domain_signup') }}" class="nav-link" role="menuitem">
          <i class="nav-icon fa fa-plus-square"></i>
          <p class="text">{% trans %}Register a domain{% endtrans %}</p>
        </a>
      </li>
    {%- endif %}
      <li class="nav-item" role="none">
        <a href="{{ url_for('sso.login') }}" class="nav-link" role="menuitem">
          <i class="nav-icon fas fa-sign-in-alt"></i>
          <p>{% trans %}Sign in{% endtrans %}</p>
        </a>
      </li>
    {#-
      User self-registration is only available when
       - Admin is available
       - Self-registration is enabled
       - The current user is not logged on
    #}
    {%- if not current_user.is_authenticated and signup_domains and config['ADMIN'] %}
      <li class="nav-item" role="none">
        <a href="{{ url_for('ui.user_signup') }}" class="nav-link" role="menuitem">
          <i class="nav-icon fa fa-user-plus"></i>
          <p class="text">{% trans %}Sign up{% endtrans %}</p>
        </a>
      </li>
    {%- endif %}
    </ul>
  </nav>
</div>